config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" } do
  end

  devise_scope :user do
    get 'signup_business', :to => 'devise/registrations#new'
    get 'signup_hunter', :to => 'devise/registrations#new'
    post 'signup_business', :to => 'devise/registrations#new'
    post 'signup_hunter', :to => 'devise/registrations#new'
  end

  as_root = -> {
    { only: %i[edit update show destroy] }
  }

  as_nested = -> {
    { only: %i[index new create] }
  }

  root to: "static_pages#index"
  
  resources :businesses do
    member do
      get :edit_job
      put :update_job
      get :edit_info
      put :update_info
      get :edit_contact
      put :update_conact
      get :edit_about
      put :update_about
      get :edit_hours
      put :update_hours
    end
    resources :positions, as_nested.()
    resources :business_hours, as_nested.()
  end

  resources :positions, as_root.()
  resources :positions do
    member do
      get :edit_info
      put :update_info
      get :edit_detail
      put :update_detail
      get :edit_about
      put :update_about
      get :edit_all
      put :update_all
    end
  end

  resources :business_hours, as_root.()

  resources :hunters do
    member do
      get :edit_profile
      put :update_profile
      get :edit_times
      put :update_times
      get :edit_cover_photo
      put :update_cover_photo
      get :edit_about
      put :update_about
    end
    resources :experiences, as_nested.()
    resources :educations, as_nested.()
    resources :languages, as_nested.()
    resources :availabilities, as_nested.()
    resources :auto_applications, as_nested.()
    resources :available_times, as_nested.()
  end

  resources :experiences, as_root.()
  resources :educations, as_root.()
  resources :languages, as_root.()
  resources :availabilities, as_root.()
  resources :auto_applications, as_root.()
  resources :available_times, as_root.()

  resources :positions do
    resources :position_applications, as_nested.()
    resources :position_advertisements, as_nested.()
  end

  resources :position_advertisements, as_root.()
  resources :position_applications, as_root.()


  resources :position_advertisements do
    resources :position_applications, as_nested.()
  end

  resources :position_applications do
    member do
      put 'reject_application'
      put 'cancel_application'
    end
  end

  resources :galleries
  resources :searches
  resources :photos
  resources :feedbacks
  resources :impressions, only: %i[create]
  resources :auto_applications

  get 'hunters/:id', to: 'hunters#show', as: :hunter_profile
  get 'dashboard/index', as: :dashboard

  get 'static_pages/index'
  get 'privacy_policy', :to => 'static_pages#privacy_policy'
  get 'general_terms', :to => 'static_pages#general_terms'
  get 'business_terms', :to => 'static_pages#business_terms'
  get 'hunter_terms', :to => 'static_pages#hunter_terms'
  get 'about', :to => 'static_pages#about'
  get 'contact', :to => 'static_pages#contact'
  get 'help', :to => 'static_pages#help'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  get 'errors/not_found'
  get 'errors/internal_server_error'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/business_type.rb
class BusinessType < ActiveRecord::Base
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_business, only: [:show, :edit, :update, :destroy]
  before_action :protect_resource, only: %i[edit update destroy]

  respond_to :html, :json

  def index
    @businesses = Business.all

    if PgSearch.multisearch(params["q"]).present?
      @businesses = PgSearch.multisearch(params["q"])
      @businesses = Business.where(id: @businesses.map(&:searchable).map(&:id))
    end

    @businesses = @businesses.near(params[:location], params[:miles]) if params[:location].present?
    @businesses = @businesses.order('updated_at DESC').paginate(:page => params[:page], :per_page => 100)

		@hash = Gmaps4rails.build_markers(@businesses) do |business, marker|
		  marker.lat business.latitude
		  marker.lng business.longitude
		  marker.infowindow render_to_string(:partial => "/businesses/map_marker", :locals => { :business => business}) 
		  marker.json({ title: business.name })
		end

    prepare_meta_tags title: "Businesses", description: "Check out all these great businesses using ApplyWithin"
  end

  def show
    prepare_meta_tags(title: @business.name,
                      description: @business.tagline,
                      image: @business.cover_image_profile
                      )

    if @business.name.present?
      @business
    else
      redirect_to edit_business_path(@business)
    end
  end

  def new
    @business = Business.new
  end

  def edit
  end

  def edit_job
    set_business
  end

  def edit_info
    set_business
  end

  def edit_contact
    set_business
  end

  def edit_about
    set_business
  end

  def edit_hours
    set_business
  end

  def create 
    @business = Business.new(business_params)
    @business.save
    respond_to do |format|
      if @business.save
        flash[:success] = 'Business was successfully created.'
        format.html { redirect_to @business }
        format.json { render :show, status: :created, location: @business }
      else
        flash[:danger] = 'There was a problem creating the Business.'
        format.html { render :new }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @business.update(business_params)
        if @business.form == "job"
          flash[:success] = 'Your profile is ready now add your job.'
          format.html { redirect_to new_business_position_path(@business) }
        else
          flash[:success] = 'Business was successfully updated.'
          format.html { redirect_to @business }
          format.json { render :show, status: :created, location: @business }
        end
      else
        flash[:danger] = 'There was a problem updating the Business.'
        format.html { render "edit_#{@business.form}" }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_job
    set_business
  end

  def update_info
    set_business
  end

  def update_contact
    set_business
  end

  def update_about
    set_business
  end

  def update_hours
    set_business
  end

  def destroy
    @business.destroy
    respond_to do |format|
      flash[:success] = 'Business was successfully destroyed.'
      format.html { redirect_to businesses_url }
      format.json { head :no_content }
    end
  end

private

  def set_business
    @business = Business.find(params[:id])
  end

  def business_params
    params.require(:business).permit(:name, :business_type, :address,
                                     :postcode, :city, :phone, :website,
                                     :about, :longitude, :latitude, :facebook, :google_plus,
                                     :instagram, :twitter, :tagline, :cover_image, :form, :source, hours_attributes: [
                                       :id, :opens_at, :closes_at
                                     ])
  end

  def protect_resource
    if !@business.owner?(current_user)
      redirect_to :root, notice: 'You do not have permission to view that page or resource.'
    end
  end

  def searched?
    params.keys.include?("search")
  end

end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business.html.erb
<div class="panel panel-default" style="border-radius:4;background-size:cover;background-image: url(<%= business.cover_image_profile %>);border:2px;border-radius:4px;box-shadow: 4px 4px 2px #888888;">
  <div class="panel-body" style="position: relative;min-height:250px;">
    <div style="margin-top:10px;background:rgba(0, 0, 0, 0.75);border-radius:4px;padding:2px;padding-left:5px;text-align:center;color:white">
      <h6 style="margin-bottom:5px;font-weight:600"><%= link_to business.name, business, style:"color:white", :target => "_blank" %></h6>
      <p style="font-size:.8em"><%= business.type %> | <%= location(business) %> </p>
    </div>
    <%= link_to 'view', business_path(business), class:"label label-default", style:'font-size:1em;border-radius:4px;color:grey;background-color:white;font-weight:600;position:absolute;bottom: 7px;right: 10px;', :target => "_blank" %>
  </div>
</div>

app/views/businesses/_map_marker.html.erb
<% if business.email.include?("colinbf") || business.email == nil %>

<% elsif business.name.present? %>

  <h5 style="text-align:center"><%= link_to business.name, business, style:"color:#FF534B;font-weight:600;font-size:1em" %><p style="color:##337ab7;margin-bottom:0px;font-size:.9em;font-weight:600"><%= business.type %> | <%= location(business) %>  </p></h5>
  <% if business.cover_image.present? %>
    <a><%= image_tag business.cover_image, style:"height:100px;width:150px;border-radius:4px;box-shadow: 4px 2px 2px #AAAAAA;text-align:center;margin-left:30px" %></a>
  <% else %>
    <a><%= image_tag ("wall.jpg"), style:"height:100px;width:150px;border-radius:4px;box-shadow: 4px 2px 2px #AAAAAA;text-align:center;margin-left:30px;" %></a>
  <% end %>  

<% end %>

app/views/businesses/_sign_up_b_feedback_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" style="color:#337AB7">Welcome</h4>
      </div>
      <div class="modal-body">
        <p>Thanks for signing up.</p>
        <p>To help with our marketing.</p>
        <%= simple_form_for(@business) do |f| %>
        <div class="form-group">
          <%= f.input :source, collection: ['Twitter', 'Facebook', 'Instagram', 'Email', 'Phone Call', 'Face to Face', 'Job Board', 'Referral', 'Google Search' ], class:'form-control', prompt:"How did you hear about us?", label: false %>
        </div>
      </div>
      <div class="modal-footer">
          <%= f.submit 'Submit', class:"btn btn-default"%>
          <% end %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
$(window).load(function(){
    $('#myModal').modal('show');
});
</script>

app/views/businesses/edit.html.erb
<!--THIS IS A BUSINESS NEW -->
<div class="row">
  <div class="col-lg-offset-3 col-lg-6">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Business</h3>
      </div>
      <%= render 'businesses/forms/form' %>

  <%= link_to 'Back', dashboard_path, class: "btn btn-default center-block" %>

  </div>
</div>

app/views/businesses/edit_about.html.erb
<div class="row">
  <div class="col-lg-offset-3 col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 id="form-title">Edit About Business
          <%= link_to 'back', :back, class:'pull-right', style:'font-size:.8em' %>
        </h3>
      </div>
      <%= simple_form_for(@business) do |f| %>
        <%= render partial: 'businesses/forms/form_about', locals: {f: f} %>
      <% end %>
  </div>
</div>

app/views/businesses/edit_all.html.erb
<!--THIS IS A BUSINESS NEW -->
<div class="row">
  <div class="col-lg-offset-3 col-lg-6">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 id="form-title">Edit Business
          <%= link_to 'back', :back, class:'pull-right', style:'font-size:.8em' %>
        </h3>
      </div>
      <%= simple_form_for(@business) do |f| %>
        <%= render partial: 'businesses/forms/form_all', locals: {f: f}  %>
      <% end %>
    </div>
  </div>
</div>

app/views/businesses/edit_contact.html.erb
<div class="row">
  <div class="col-lg-offset-3 col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 id="form-title">Edit Business Contact
          <%= link_to 'back', :back, class:'pull-right', style:'font-size:.8em' %>
        </h3>
      </div>
      <%= simple_form_for(@business) do |f| %>
        <%= render partial: 'businesses/forms/form_contact', locals: {f: f} %>
      <% end %>
  </div>
</div>

app/views/businesses/edit_hours.html.erb
<div class="row">
  <div class="col-lg-offset-3 col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 id="form-title">Edit Business Opening Hours
          <%= link_to 'back', :back, class:'pull-right', style:'font-size:.8em' %>
        </h3>
      </div>
      <%= form_for(@business) do |f| %>
        <%= render partial: 'businesses/forms/form_hours', locals: {f: f} %>
      <% end %>
  </div>
</div>

app/views/businesses/edit_info.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-lg-offset-3 col-lg-6 col-md-6 col-sm-8 col-xs-10">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 id="form-title">Edit Business Details
          <%= link_to 'back', :back, class:'pull-right', style:'font-size:.8em' %>
        </h3>
      </div>
      <%= simple_form_for(@business) do |f| %>
        <%= render partial: 'businesses/forms/form_info', locals: {f: f} %>
      <% end %>
  </div>
</div>

app/views/businesses/edit_job.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-lg-offset-3 col-lg-6 col-md-6 col-sm-8 col-xs-10">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 id="form-title">Create Business Profile
          <%= link_to 'back', :back, class:'pull-right', style:'padding-top:5px;font-size:.8em' %>
        </h3>
      </div>
      <%= simple_form_for(@business) do |f| %>
        <%= render partial: 'businesses/forms/form_job', locals: {f: f} %>
      <% end %>
    </div>
  </div>
</div>

<% if !@business.source.present? %>
  <%= render partial: 'sign_up_b_feedback_modal' %>
<% end %>

app/views/businesses/index.html.erb
<div class="container" style="margin-top:-20px">

<div class="row search-bar">
  <div class="col-lg-offset-2 col-lg-8 col-md-offset-2 col-md-8 col-sm-offset-1 col-sm-10 col-xs-offset-1 col-xs-10">
    <%= form_tag businesses_path, class: 'form-inline', :method => :get do %>
      <div class="form-group">
        <%= text_field_tag :q, params[:q], placeholder: "What?", class:"form-control"  %>
      </div>
      <div class="form-group hidden-xs">
        <%= text_field_tag :location, params[:location], placeholder: "Where?", class:"form-control" %>
      </div>
      <div class="form-group hidden-xs">
        <%= select_tag(:miles, options_for_select([1,2.5,5,10,15,20]), options = {class:'form-control'})  %><label style="margin-left:10px">miles</label>
      </div>
      <%= button_tag(class: 'btn btn-default') do %><span class="glyphicon glyphicon-search" aria-hidden="true"></span><% end %>
    <% end %>
  </div>
</div>

<div class="collapse collapse in" id="collapseExample">
  <div class="panel-body">
    <div class="col-lg-offset-1 col-lg-10">
      <div id="multi_markers" class="map" style='width:100%;height:300px;'></div>
    </div>
  </div>
</div>

<button class="btn btn-default pull-right" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
  Map
</button>

    <h5>Results:&nbsp;<%= @businesses.count %> <%= params[:q] %> <%= params[:location] %></h5>
    <%= will_paginate @businesses, :page_links => true, style:"margin:0px" %>
    <hr>
  <div class="row">
    <% @businesses.each do |business| %>
      <% if business.name.present? %>
        <div class="col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0 col-lg-3 col-md-4 col-sm-6 col-xs-12">
          <%= render partial: 'businesses/business', locals: {business: business} %>
        </div>
      <% end %>
    <% end %>
  </div>
    <%= will_paginate @businesses, :page_links => true, style:"margin:0px", class:"pull-right" %>
</div>

<script type="text/javascript">
  var handler = Gmaps.build('Google', { markers: { clusterer: { maxZoom: 12, gridSize: 100 }}});
  handler.buildMap({ 
  	provider: { mapTypeId: google.maps.MapTypeId.ROADMAP, maxZoom: 16 }, 
  	internal: {id: 'multi_markers'}}, function(){
    var markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/businesses/new.html.erb
<!--THIS IS A BUSINESS NEW -->
<div class="row">
  <div class="col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-lg-offset-3 col-lg-6 col-md-6 col-sm-8 col-xs-10">

    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Business
        </h3>
      </div>

      <%= render 'businesses/forms/form_info' %>

  </div>
</div>

app/views/businesses/show.html.erb
  <div class="cover_image" style="background-image: url(<%= @business.cover_image_profile %>);">

    <div class="container" id="main">
        <div class="row">
          <%= render partial: "businesses/profile/business_info", locals: { business: @business } %>
        </div>
    </div>

  </div>


<div class="container" id="main">

  <div class="row" style="margin-top:20px">
    <div class="col-lg-8">
      <%= render partial: "businesses/profile/business_jobs", locals: { business: @business } %>
      <%= render partial: "businesses/profile/business_gallery", locals: { business: @business } %>
      <%= render partial: "businesses/profile/business_about", locals: { business: @business } %>
    </div>
    <div class="col-lg-4">
      <%= render partial: "businesses/profile/business_contact", locals: { business: @business } %>
      <%= render partial: "businesses/profile/business_hours", locals: { business: @business } %>
      <%= render partial: "businesses/profile/business_map", locals: { business: @business } %>
    </div>
  </div>

  
  <% if @business.email.include?("@willywonka") %>
    <div class="col-lg-10 col-lg-offset-1">
      <%= render partial: "businesses/profile/business_claim_btn" %>
    </div>
  <% end %>
  
</div><!--/main-->

<!-- Modal -->
<% if @business.email.include?("@applywithin.co.uk") %>
<%= render partial: "businesses/profile/business_modal" %>
<% end %>