config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" } do
  end

  devise_scope :user do
    get 'signup_business', :to => 'devise/registrations#new'
    get 'signup_hunter', :to => 'devise/registrations#new'
    post 'signup_business', :to => 'devise/registrations#new'
    post 'signup_hunter', :to => 'devise/registrations#new'
  end

  as_root = -> {
    { only: %i[edit update show destroy] }
  }

  as_nested = -> {
    { only: %i[index new create] }
  }

  root to: "static_pages#index"
  
  resources :businesses do
    member do
      get :edit_job
      put :update_job
      get :edit_info
      put :update_info
      get :edit_contact
      put :update_conact
      get :edit_about
      put :update_about
      get :edit_hours
      put :update_hours
    end
    resources :positions, as_nested.()
    resources :business_hours, as_nested.()
  end

  resources :positions, as_root.()
  resources :positions do
    member do
      get :edit_info
      put :update_info
      get :edit_detail
      put :update_detail
      get :edit_about
      put :update_about
      get :edit_all
      put :update_all
    end
  end

  resources :business_hours, as_root.()

  resources :hunters do
    member do
      get :edit_profile
      put :update_profile
      get :edit_times
      put :update_times
      get :edit_cover_photo
      put :update_cover_photo
      get :edit_about
      put :update_about
    end
    resources :experiences, as_nested.()
    resources :educations, as_nested.()
    resources :languages, as_nested.()
    resources :availabilities, as_nested.()
    resources :auto_applications, as_nested.()
    resources :available_times, as_nested.()
  end

  resources :experiences, as_root.()
  resources :educations, as_root.()
  resources :languages, as_root.()
  resources :availabilities, as_root.()
  resources :auto_applications, as_root.()
  resources :available_times, as_root.()

  resources :positions do
    resources :position_applications, as_nested.()
    resources :position_advertisements, as_nested.()
  end

  resources :position_advertisements, as_root.()
  resources :position_applications, as_root.()


  resources :position_advertisements do
    resources :position_applications, as_nested.()
  end

  resources :position_applications do
    member do
      put 'reject_application'
      put 'cancel_application'
    end
  end

  resources :galleries
  resources :searches
  resources :photos
  resources :feedbacks
  resources :impressions, only: %i[create]
  resources :auto_applications

  get 'hunters/:id', to: 'hunters#show', as: :hunter_profile
  get 'dashboard/index', as: :dashboard

  get 'static_pages/index'
  get 'privacy_policy', :to => 'static_pages#privacy_policy'
  get 'general_terms', :to => 'static_pages#general_terms'
  get 'business_terms', :to => 'static_pages#business_terms'
  get 'hunter_terms', :to => 'static_pages#hunter_terms'
  get 'about', :to => 'static_pages#about'
  get 'contact', :to => 'static_pages#contact'
  get 'help', :to => 'static_pages#help'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  get 'errors/not_found'
  get 'errors/internal_server_error'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contact.html.erb
<div class="container" id="main">
  <div class="row">
    <div class="col-lg-12">
      <h2 class='page-header'>Contact</h2>
    </div>
  </div>
</div>

app/views/static_pages/help.html.erb
<div class="container" id="main">
  <div class="row">
    <div class="col-lg-12">
      <h2 class='page-header'>Help</h2>
    </div>
  </div>
</div>

app/views/static_pages/hunter_terms.html.erb
<div class="container" id="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-12 col-xs-12">

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 id="form-title">Registered Job Hunter Terms</h3>
          <p>ApplyWithin.co.uk</p>
        </div>
          <div class="panel-body" style="padding:20px;padding-top:10px">
            <h5 style="font-weight:600;color:#428bca">1.	THESE TERMS</h5>
            <ul>
              <li style="font-size:.8em"><span style="font-weight:600">1.1	What these terms cover.</span> These are the terms and conditions on which we supply services to you. Our services are designed to enable you, as a registered job hunter, to identify vacancies within registered businesses.</li>
              <li style="font-size:.8em"><span style="font-weight:600">1.2	Why you should read them.</span> Please read these terms carefully before registering to use this website. By registering you are confirming your acceptance of these terms.</li>
              <li style="font-size:.8em"><span style="font-weight:600">1.3	Changes to these terms. </span> We may revise these terms at any time and will notify you of these changes by posting a notification on our site which will appear as a “pop up” when you next log in. Please check this page from time to time to take notice of any changes we have made, as they are binding on you.</li>
            </ul> 
            <h5 style="font-weight:600;color:#428bca">2.	INFORMATION ABOUT US AND HOW TO CONTACT US</h5>
            <ul>
              <li style="font-size:.8em"><span style="font-weight:600">2.1	Who we are.</span> We are thefreejobnetwork Limited, a company registered in England under company number 9782273 and have our registered office at 71-75 Shelton Street, Covent Garden, London, WC2H 9JQ.</li>
              <li style="font-size:.8em"><span style="font-weight:600">2.2	How to contact us. </span> You can contact us by writing to us at <a style="color:#428bca">contact@applywithin.co.uk</a> or WC2H 9JQ.</li>
              <li style="font-size:.8em"><span style="font-weight:600">2.3	How we may contact you. </span> If we have to contact you we will do so by writing to you at the email address or postal address you provide to us. </li>
              <li style="font-size:.8em"><span style="font-weight:600">2.4	"Writing" includes emails. </span> When we use the words "writing" or "written" in these terms, this includes emails.</li>
            </ul>
            <h5 style="font-weight:600;color:#428bca">3.	CONTRACT WITH YOU AND YOUR ACCOUNT</h5>
            <ul>
              <li style="font-size:.8em"><span style="font-weight:600">3.1	Terms of Use and Privacy Policy. </span> You have read, understood and agree to the <%= link_to "Terms of Use", general_terms_path, style:"color:#FF534B;font-weight:600" %> and <%= link_to "Privacy Policy", privacy_policy_path, style:"color:#FF534B;font-weight:600" %> which are deemed incorporated into these terms. We will use the personal information you provide to us in connection with the services in accordance with the Privacy Policy.</li>
              <li style="font-size:.8em"><span style="font-weight:600">3.2	Your Account. </span>  In order to use parts of the services, you must register with us and create a user profile ("User Account") which will require a password. The name that you register with must be your own real name and you agree not to:
                <ul>
              <li style="font-size:.8em">(a)	create or use the name of another person with the intention of impersonating that person;</li>
              <li style="font-size:.8em">(b)	use a name which is subject to any rights of a person other than you without appropriate authorisation; or</li>
              <li style="font-size:.8em">(c)	use a name which is offensive or inflammatory as deemed by us in our sole discretion.</li>
                </ul>
              We may refuse registration of, or cancel a User Account and disable any User Account, if in our reasonable opinion you fail to comply with these terms, the Terms of Use or the Privacy Policy, and such termination and/or restriction will be effective immediately.</li>
              <li style="font-size:.8em"><span style="font-weight:600">3.3	Your responsibilities.</span>   Do not reveal your User Account information to anyone else. You are solely responsible for:</li>
              <ul>
              <li style="font-size:.8em">(a)	maintaining the confidentiality and security of your User Account and should use your own virus protection software. If you become aware of any unauthorised use of your password or User Account, you agree to notify us immediately by email to  <a style="color:#428bca">contact@applywithin.co.uk</a>. You agree not to use another user’s account without the express permission of that user;</li>
              <li style="font-size:.8em">(b)	configuring your information technology, computer programmes and platform in order to access the site; and</li>
              <li style="font-size:.8em">(c)	using the services in a professional manner.</li>
              </ul>
              <li style="font-size:.8em"><span style="font-weight:600">3.4	The services.</span>   The services we provide are provided “as is” and all warranties, conditions, representations or other terms, whether express or implied, are excluded by us to the fullest extent permitted by law. We do not control the actual transaction between registered businesses and registered job hunters and as a result, we are not responsible for user content, the quality, safety or legality of the jobs or job hunter profiles posted, the truth or accuracy of registered positions, the ability of businesses to offer job opportunities to job hunters or the ability of job hunters to fill job vacancies and we make no representations about any jobs, or job hunter profiles or user content.</li>
              <li style="font-size:.8em"><span style="font-weight:600">3.5	Notices.</span>  You agree that we can use our website and your contact email address to provide you with notices. If the contact information you provide isn't up to date, you may miss out on these notices. You agree to keep your contact information up to date. </li>
            </ul>
          <h5 style="font-weight:600;color:#428bca">4.	VACANCIES AND APPLICATIONS</h5>
            <ul>
              <li style="font-size:.8em"><span style="font-weight:600">4.1	Vacancies.</span>   You acknowledge that we are not responsible for the content of any job vacancy advertising and that accordingly it is a matter for you to satisfy yourself as to the suitability of the job vacancy and the identity of the business. There may be certain eligibility requirements, for example, a minimum age for a particular job. To use the services, you agree that you are the minimum age or older (if this is a particular requirement).</li>
              <li style="font-size:.8em"><span style="font-weight:600">4.2	Applications.</span>   If you submit an application for a vacancy which has been posted on the site or you make your profile page available to registered businesses, you agree that:
              <ul>
                <li style="font-size:.8em">(a)	You have read and understood the requirements for the job vacancy;</li>
                <li style="font-size:.8em">(b)	The information that you provide as part of the application and/or within your profile page is up to date and is a true and accurate reflection of your employment, education, experience and training, and current or previous positions and qualifications and that your personal details are correct and can be used by the business to contact you;</li>
                <li style="font-size:.8em">(c)	The image that you have used (if any) is a true likeness.</li>
              </ul>
If you submit any information that is found to be false, we reserve the right to deny you access to the site and services.</li>
              <li style="font-size:.8em"><span style="font-weight:600">4.3	Requests for information.</span>   Please note that applications and profile pages are assessed by the relevant registered business and all decisions relating to such applications are taken by the relevant business and not by us. Accordingly, any requests for information relating to applications that have been made should be addressed to the business directly.</li>
              <li style="font-size:.8em"><span style="font-weight:600">4.4	Reasons we may suspend the supply of services.</span>  We may have to suspend the supply of services to:</li>
                <ul>
                <li style="font-size:.8em">(a)	deal with technical problems or make minor technical changes on our website; or</li>
                <li style="font-size:.8em">(b)	update the website to reflect changes in relevant laws and regulatory requirements.</li>
                </ul>
            </ul>
            <h5 style="font-weight:600;color:#428bca">5.	RIGHTS TO END THE CONTRACT</h5>
            <ul>
              <li style="font-size:.8em"><span style="font-weight:600">5.1</span>	We can each end this contract at any time with notice to the other.</span>  On termination, you lose the right to access or use the services. </li>
              <li style="font-size:.8em"><span style="font-weight:600">5.2</span>	If you wish to cancel or delete your User Account, you can do this by logging into the site and following the instructions stated within the site.  You understand and acknowledge that you have no ownership rights in your User Account and that if you cancel or delete your User Account or your User Account is terminated, all your account information, including your profiles and applications will be marked as deleted in, and removed from, our databases and will be removed from the site as soon as reasonably possible.</li>
              <li style="font-size:.8em"><span style="font-weight:600">5.3</span>	We reserve the right to disable your User Account and all of your information after a significant duration of inactivity.</li>
              <li style="font-size:.8em"><span style="font-weight:600">5.4</span>	Notwithstanding termination of your User Account, third parties may retain saved copies of your information, for example, registered businesses that you have applied to.</li>
            </ul>
            <h5 style="font-weight:600;color:#428bca">6.	OUR RESPONSIBILITY FOR LOSS OR DAMAGE SUFFERED BY YOU</h5>
            <ul>
              <li style="font-size:.8em"><span style="font-weight:600">6.1	Foreseeable loss and damage.</span> If either we or you fail to comply with these terms, neither of us will be responsible for any loss that the other suffers as a result, except for losses which are foreseeable. Loss or damage is foreseeable if it was an obvious consequence of failure to comply with these terms or if it was contemplated by you and us at the time we entered into these terms.</li>
              <li style="font-size:.8em"><span style="font-weight:600">6.2	We are not liable for business losses.</span> You agree not to use the site for any commercial or business purposes. If you use the products for any commercial or business purpose we will have no liability to you for any loss of profit, loss of business, business interruption, or loss of business opportunity.</li> 
              <li style="font-size:.8em"><span style="font-weight:600">6.3</span>	Nothing in these terms of use excludes or limits our liability for death or personal injury arising from our negligence, or our fraud or fraudulent misrepresentation, or any other liability that cannot be excluded or limited by law.</li>
            </ul>
            <h5 style="font-weight:600;color:#428bca">7.	OTHER IMPORTANT TERMS</h5>
            <ul>
              <li style="font-size:.8em"><span style="font-weight:600">7.1	We may transfer this agreement to someone else.</span> We may transfer our rights and obligations under these terms to another organisation as a result of a sale or transfer of our business or change in ownership of our business.</li>
              <li style="font-size:.8em"><span style="font-weight:600">7.2	Nobody else has any rights under this contract.</span> This contract is between you and us. No other person shall have any rights to enforce any of its terms.</li>
              <li style="font-size:.8em"><span style="font-weight:600">7.3	If a court finds part of this contract illegal, the rest will continue in force.</span> Each of the paragraphs of these terms operates separately. If any court or relevant authority decides that any of them are unlawful, the remaining paragraphs will remain in full force and effect.</li>
              <li style="font-size:.8em"><span style="font-weight:600">7.4	Even if we delay in enforcing this contract, we can still enforce it later.</span> If we do not insist immediately that you do anything you are required to do under these terms, or if we delay in taking steps against you in respect of your breaking this contract, that will not mean that you do not have to do those things and it will not prevent us taking steps against you at a later date.</li>
              <li style="font-size:.8em"><span style="font-weight:600">7.5	Which laws apply to this contract and where you may bring legal proceedings.</span> These terms and their subject matter and formation are governed by Scots law. You and we both agree that the Scottish courts will have non-exclusive jurisdiction. However, if you are a consumer and a resident of Northern Ireland you may also bring proceedings in Northern Ireland, or if you are a consumer and resident of England, you may also bring proceedings in England.</li>
            </ul>

          </div>
      </div>

    </div>
  </div>
</div>

app/views/static_pages/privacy_policy.html.erb
<div class="container" id="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-12 col-xs-12">

      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 id="form-title">Privacy Policy</h3>
          <p>ApplyWithin.co.uk</p>
        </div>
        <div class="panel-body" style="padding:20px;padding-top:10px">
          <p style="font-size:.8em">This privacy policy applies to information gathered by us in connection with our website: <a style="color:#FF534B">www.applywithin.co.uk</a> (our site).
          </br></br>

          We are committed to protecting your privacy and take our responsibilities regarding the security of your information very seriously.  This policy explains how we use your information and how we protect your privacy.
          </br></br>

          This policy (together with our terms of use <%= link_to "Terms of Use", general_terms_path, style:"color:#FF534B;font-weight:600" %> and any other documents referred to) sets out the basis on which any personal information we collect from you, or that you provide to us including through your use of our site will be processed by us. 
          </br></br>

          This site is operated by thefreejobnetwork Limited. We are registered in England under company number 9782273 and have our registered office at 71-75 Shelton Street, Covent Garden, London, WC2H 9JQ. Our main trading address is  71-75 Shelton Street, Covent Garden, London, WC2H 9JQ. We are the data controller for the purposes of the Data Protection Act 1998 (the “Act”) in respect of personal information we obtain in connection with our site. 
          </br></br>

          If you register on our site, our <%= link_to " Business Terms ", business_terms_path, style:"color:#FF534B;font-weight:600" %> or <%= link_to " Job Hunter Terms ", hunter_terms_path, style:"color:#FF534B;font-weight:600" %> will apply to your registration.</p>

          <h5 style="color:#337AB7;font-weight:600;margin-top:30px">What information do we collect about you?</h5>
          <p style="font-size:.8em">To do any of the following things, you will need to provide us with personal information:</p>
          <ul>
            <li style="font-size:.8em">Fill in registration forms to register as:</li>
            <li style="font-size:.8em">a business and create a public profile page on our site containing general information about your business and job opportunities offered by your business; or</li>
            <li style="font-size:.8em">a job hunter and create a private profile page on our site containing your personal information which will be made available to registered businesses when you submit a job application;</li>
            <li style="font-size:.8em">Sign up to receive emails, for example, job alert emails;</li>
            <li style="font-size:.8em">Make use of our site and services;</li>
            <li style="font-size:.8em">Contact us; or</li>
            <li style="font-size:.8em">Provide feedback on the site.</li>
          </ul>

          <p style="font-size:.8em">The information you may be asked to provide may include:</p>
          <ul>
            <li style="font-size:.8em">As a business: your business name, business type, business address (including city and postcode), email address, telephone number, details of your website (and links to your Facebook page, Twitter feed) and details about your business, for example, opening times; & details of the job opportunity, including the job title and description, the roles and responsibilities, the job type, for example, whether it is customer facing, job hours, job wages / tips and whether there are any age restrictions;</li>
            <li style="font-size:.8em">As a job hunter, your first name and last name, date of birth, nationality, location, email address, telephone number, your driving licence, photograph, details of your weekly availability, details of your education and work experience, details of your personal interests and your personal description, for example, about me, interests and hobbies.</li>
          </ul>

          <p style="font-size:.8em">When you use our site, we or our third party providers may collect, process and store the following type of information:</p>
          <ul>
            <li style="font-size:.8em">Information about your computer and your visits to our site, such as your Internet protocol (IP) address used to connect your computer to the Internet, geographical location, browser type and version, your login information, length of visit and number of pages viewed, to administer our site and improve our site;</li>
            <li style="font-size:.8em">Information relating to the activities you carry out via our site, including, as a registered business, information relating to any jobs you register on the site and, as a registered job hunter, any jobs which you apply for as a job hunter. We will use information to provide information to you and to communicate with you when necessary;</li>
            <li style="font-size:.8em">Information that you provide to us for the purpose of registering with us; and</li>
            <li style="font-size:.8em">Information that you provide when you contact us by email or otherwise.</p>
          </ul>


          <h5 style="color:#337AB7;font-weight:600;margin-top:30px">How will we use the information about you?</h5>
          <p style="font-size:.8em">We use the information we hold about you in the following ways:<p style="font-size:.8em">
          <ul>
            <li style="font-size:.8em">If you are a registered job hunter, to provide you with a private and secure area to post and modify your submissions to our site (such as profile pages and job applications) and make these available to registered businesses and if you are a registered business, to make your registered positions and job opportunity details available to registered job hunters;</li>
            <li style="font-size:.8em">To personalise your visits to the site to improve the services provided to you;</li>
            <li style="font-size:.8em">To answer any questions you may raise or respond to any comments you may send to us;</li>
            <li style="font-size:.8em">To notify you about changes to our service or the functionality of our site;</li>
            <li style="font-size:.8em">To ensure that you are complying with our terms and conditions and to comply with our statutory and regulatory obligations;</li>
            <li style="font-size:.8em">To help us improve the structure, layout and usability of our site through monitoring your usage to ensure that content is presented in the most effective manner for you and for your computer;</li>
            <li style="font-size:.8em">To administer our site and for internal operations and as part of our efforts to keep our site safe and secure;</li>
            <li style="font-size:.8em">To keep you informed about us;</li>
            <li style="font-size:.8em">To measure or understand the effectiveness of advertising we serve to you and others, and to deliver relevant advertising to you on the site.</li>
          </ul>

          <p style="font-size:.8em">Our site may, from time to time, contain links to and from the websites of our partner networks, advertisers and affiliates. If you follow a link to any of these websites, please note that these websites have their own privacy policies and that we do not accept any responsibility or liability for these policies.  Please check these policies before you submit any personal data to these websites.</p>

          <p style="font-size:.8em">We do not disclose information about identifiable individuals to any advertisers on our site, but if we allow advertising on our site we may provide advertisers with aggregate information about our users (for example, we may inform them that 500 men aged under 30 have clicked on their advertisement on any given day).</p>

          <p style="font-size:.8em">We may disclose your personal information to third parties if we are under a duty to disclose or share your personal data in order to comply with any legal obligation, or in order to enforce or apply our <%= link_to "Terms of Use", general_terms_path, style:"color:#FF534B;font-weight:600" %> or our <%= link_to " Business Terms ", business_terms_path, style:"color:#FF534B;font-weight:600" %> or <%= link_to " Job Hunter Terms ", hunter_terms_path, style:"color:#FF534B;font-weight:600" %>  and other agreements; or to protect our rights, or the rights, property, or safety of our customers, or others.</p>

          <h5 style="color:#337AB7;font-weight:600;margin-top:30px">Keeping your information up to date</h5>
          <p style="font-size:.8em">We want to make sure that your personal information is accurate and up to date. If, for any reason, you are concerned that personal information held by us is not correct, or if you want to review, correct, update, change or delete your account profile information at any time, please visit our site and log in to review and change your personal information, account information and if you wish, delete it (please note that we may retain records of your previous user account profiles, which will not be accessible by third parties, for audit and recordkeeping purposes). If you prefer, you can ask us to correct or remove information that you think is inaccurate at any time by emailing us at <a style="color:#FF534B">contact@applywithin.co.uk</a>.</p> 

          <p style="font-size:.8em">You are entitled to ask for a copy of your information (for which we may charge a small fee) and to correct any inaccuracies. This data protection notice may change and therefore you should review it regularly. We will of course notify you of any changes where we are required to do so. If you have questions about your personal data or our privacy policy, please contact us at <a style="color:#FF534B">contact@applywithin.co.uk</a></p>

          <h5 style="color:#337AB7;font-weight:600;margin-top:30px">Cookies</h5>
          <p style="font-size:.8em">Our site uses cookies to distinguish you from other users of our site. A cookie is a small text file that is placed on your computer’s hard drive by your web browser. Cookies allow us to identify your computer and find out details about your visit. This helps us to provide you with a good experience when you browse our website and also allows us to improve our site. For further information about cookies visit: <a style="color:#FF534B">http://www.aboutcookies.org/</a>
          Please note that most Internet browsers are set to accept cookies automatically but usually you can set your browser not to accept cookies and the website we have referred to above will give you instructions on how to do so. However, in a few cases some of the features on our site may not function as a result.</p>

          <h5 style="color:#337AB7;font-weight:600;margin-top:30px">Where we store your personal data</h5>
          <p style="font-size:.8em">The personal data that we collect from you may be transferred to, and stored at, a location outside the European Economic Area (“EEA”). It may also be processed by staff located outside the EEA who work for us or for one of our suppliers that we engage to help provide certain services. By submitting your personal data to us through our site, you agree to this transfer, storing or processing. We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this privacy policy.
          All information you provide to us is stored on our secure servers and we will take all reasonable care to make our site safe and secure. Unfortunately, the transmission of information via the Internet is not completely secure. Although we will do our best to protect your personal data, we cannot guarantee the security of your data transmitted to our site; any transmission is at your own risk. Once we have received your information, we will use procedures and security features to try to prevent unauthorised access.</p>

          <h5 style="color:#337AB7;font-weight:600;margin-top:30px">Changes to our privacy policy</h5>
          <p style="font-size:.8em">Any changes we may make to our privacy policy in the future will be posted as a notification on our site which you will appear as a “pop up” when you next log in as a registered user. If you are using the site as a guest, please check this page from time to time to take notice of any updates or changes to our privacy policy, as they are binding on you.
          We may transfer, sell or assign any of the information described in this policy to third parties as a result of a sale or transfer of our business or change in ownership of our business. 
          Contact us
          Questions, comments and requests regarding this privacy policy are welcomed and should be addressed to <a style="color:#FF534B">contact@applywithin.co.uk</a>.
          </br></br>
          Effective Date: September 2015</p>

        </div>
      </div>

    </div>
  </div>
</div>