config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" } do
  end

  devise_scope :user do
    get 'signup_business', :to => 'devise/registrations#new'
    get 'signup_hunter', :to => 'devise/registrations#new'
    post 'signup_business', :to => 'devise/registrations#new'
    post 'signup_hunter', :to => 'devise/registrations#new'
  end

  as_root = -> {
    { only: %i[edit update show destroy] }
  }

  as_nested = -> {
    { only: %i[index new create] }
  }

  root to: "static_pages#index"
  
  resources :businesses do
    member do
      get :edit_job
      put :update_job
      get :edit_info
      put :update_info
      get :edit_contact
      put :update_conact
      get :edit_about
      put :update_about
      get :edit_hours
      put :update_hours
    end
    resources :positions, as_nested.()
    resources :business_hours, as_nested.()
  end

  resources :positions, as_root.()
  resources :positions do
    member do
      get :edit_info
      put :update_info
      get :edit_detail
      put :update_detail
      get :edit_about
      put :update_about
      get :edit_all
      put :update_all
    end
  end

  resources :business_hours, as_root.()

  resources :hunters do
    member do
      get :edit_profile
      put :update_profile
      get :edit_times
      put :update_times
      get :edit_cover_photo
      put :update_cover_photo
      get :edit_about
      put :update_about
    end
    resources :experiences, as_nested.()
    resources :educations, as_nested.()
    resources :languages, as_nested.()
    resources :availabilities, as_nested.()
    resources :auto_applications, as_nested.()
    resources :available_times, as_nested.()
  end

  resources :experiences, as_root.()
  resources :educations, as_root.()
  resources :languages, as_root.()
  resources :availabilities, as_root.()
  resources :auto_applications, as_root.()
  resources :available_times, as_root.()

  resources :positions do
    resources :position_applications, as_nested.()
    resources :position_advertisements, as_nested.()
  end

  resources :position_advertisements, as_root.()
  resources :position_applications, as_root.()


  resources :position_advertisements do
    resources :position_applications, as_nested.()
  end

  resources :position_applications do
    member do
      put 'reject_application'
      put 'cancel_application'
    end
  end

  resources :galleries
  resources :searches
  resources :photos
  resources :feedbacks
  resources :impressions, only: %i[create]
  resources :auto_applications

  get 'hunters/:id', to: 'hunters#show', as: :hunter_profile
  get 'dashboard/index', as: :dashboard

  get 'static_pages/index'
  get 'privacy_policy', :to => 'static_pages#privacy_policy'
  get 'general_terms', :to => 'static_pages#general_terms'
  get 'business_terms', :to => 'static_pages#business_terms'
  get 'hunter_terms', :to => 'static_pages#hunter_terms'
  get 'about', :to => 'static_pages#about'
  get 'contact', :to => 'static_pages#contact'
  get 'help', :to => 'static_pages#help'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  get 'errors/not_found'
  get 'errors/internal_server_error'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/views/shared/_footer.html.erb
<footer>
  <div class="row">
    <div class="col-md-offset-3 col-lg-offset-3 col-lg-6 col-md-6">
      <ul class="list-inline">
        <hr>
        <li><%= link_to "About", about_path %></li>
        <li><%= mail_to "contact@applywithin.co.uk", 'Contact' %></li>
        <li><p>Copyright &copy; thefreejobnetwork 2016</p></li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'ApplyWithin', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

      <% if user_signed_in? %>
        <li><%= link_to :dashboard do %><i class="fa fa-list-alt"></i> Applications<% end %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to current_user.group do %><i class="fa fa-user"></i>&nbsp;&nbsp;&nbsp;View Profile<% end %></li>
            <% if current_user.group.class.to_s == "Business" %> 
              <li><%= link_to edit_info_business_path(current_user.group) do %><i class="fa fa-pencil-square-o"></i>&nbsp;&nbsp;&nbsp;Edit Profile<% end %></li>
            <% else %>
              <li><%= link_to edit_profile_hunter_path(current_user.group) do %><i class="fa fa-pencil-square-o"></i>&nbsp;&nbsp;&nbsp;Edit Profile<% end %></li>
            <% end %>
            <li><%= link_to edit_user_registration_path(current_user.group) do %><i class="fa fa-list"></i>&nbsp;&nbsp;&nbsp;Edit Settings<% end %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to destroy_user_session_path, method: :delete do %><i class="fa fa-sign-out"></i>&nbsp;&nbsp;&nbsp;Sign Out<% end %></li>
          </ul>
        </li>

      <% else %>

        <li><%= link_to 'Sign In', new_user_session_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to 'Add Job', signup_business_path %></li>

      <% end %>

        <li>
          <form class="navbar-form navbar-right" role="search">
            <%= link_to positions_path, class: 'btn btn-large' do %><i class="fa fa-search"></i><% end %>
          </form>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>