config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: "users/registrations" } do
  end

  devise_scope :user do
    get 'signup_business', :to => 'devise/registrations#new'
    get 'signup_hunter', :to => 'devise/registrations#new'
    post 'signup_business', :to => 'devise/registrations#new'
    post 'signup_hunter', :to => 'devise/registrations#new'
  end

  as_root = -> {
    { only: %i[edit update show destroy] }
  }

  as_nested = -> {
    { only: %i[index new create] }
  }

  root to: "static_pages#index"
  
  resources :businesses do
    member do
      get :edit_job
      put :update_job
      get :edit_info
      put :update_info
      get :edit_contact
      put :update_conact
      get :edit_about
      put :update_about
      get :edit_hours
      put :update_hours
    end
    resources :positions, as_nested.()
    resources :business_hours, as_nested.()
  end

  resources :positions, as_root.()
  resources :positions do
    member do
      get :edit_info
      put :update_info
      get :edit_detail
      put :update_detail
      get :edit_about
      put :update_about
      get :edit_all
      put :update_all
    end
  end

  resources :business_hours, as_root.()

  resources :hunters do
    member do
      get :edit_profile
      put :update_profile
      get :edit_times
      put :update_times
      get :edit_cover_photo
      put :update_cover_photo
      get :edit_about
      put :update_about
    end
    resources :experiences, as_nested.()
    resources :educations, as_nested.()
    resources :languages, as_nested.()
    resources :availabilities, as_nested.()
    resources :auto_applications, as_nested.()
    resources :available_times, as_nested.()
  end

  resources :experiences, as_root.()
  resources :educations, as_root.()
  resources :languages, as_root.()
  resources :availabilities, as_root.()
  resources :auto_applications, as_root.()
  resources :available_times, as_root.()

  resources :positions do
    resources :position_applications, as_nested.()
    resources :position_advertisements, as_nested.()
  end

  resources :position_advertisements, as_root.()
  resources :position_applications, as_root.()


  resources :position_advertisements do
    resources :position_applications, as_nested.()
  end

  resources :position_applications do
    member do
      put 'reject_application'
      put 'cancel_application'
    end
  end

  resources :galleries
  resources :searches
  resources :photos
  resources :feedbacks
  resources :impressions, only: %i[create]
  resources :auto_applications

  get 'hunters/:id', to: 'hunters#show', as: :hunter_profile
  get 'dashboard/index', as: :dashboard

  get 'static_pages/index'
  get 'privacy_policy', :to => 'static_pages#privacy_policy'
  get 'general_terms', :to => 'static_pages#general_terms'
  get 'business_terms', :to => 'static_pages#business_terms'
  get 'hunter_terms', :to => 'static_pages#hunter_terms'
  get 'about', :to => 'static_pages#about'
  get 'contact', :to => 'static_pages#contact'
  get 'help', :to => 'static_pages#help'

  match '/contacts', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  get 'errors/not_found'
  get 'errors/internal_server_error'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :hunter
  delegate :user, to: :hunter

  validates :institution, :qualification, :subject, :result, :start_date, :end_date, presence: true

  def formatted_start_date
    start_date.strftime("%b %Y") if start_date
  end

  def formatted_end_date
    end_date.strftime("%b %Y") if end_date
  end

end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController

  def index
    get_hunter.educations
  end

  def show
    get_education
  end

  def new
    new_education
  end

  def edit
    get_education
  end

  def create
    respond_to do |format|
      if new_education(education_params).save
        flash[:success] = 'Education was successfully added.'
        format.html { redirect_to current_user.group }
        format.json { render :show, status: :created, location: @hunter }
      else
        flash[:danger] = 'There was a problem creating the Education, please try again.'
        format.html { render :new }
        format.json { render json: @hunter.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if get_education.update_attributes(education_params)
        flash[:success] = 'Education was successfully updating.'
        format.html { redirect_to current_user.group }
        format.json { render :show, status: :created, location: @position }
      else
        flash[:danger] = 'There was a problem updating the Education, please try again.'
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    get_education.destroy
    respond_to do |format|
      flash[:success] = 'Education was successfully deleted.'
      format.html { redirect_to current_user.group }
      format.json { head :no_content }
    end
  end

private

  def new_education(vals={})
    @education ||= get_hunter.educations.build(vals)
  end

  def get_education
    @education ||= Education.find(params[:id])
  end

  def get_hunter
    @hunter ||= Hunter.find(params[:hunter_id])
  end

  def education_params
    params.require(:education).permit(:institution, :qualification, :subject, :result, :start_date, :end_date, :comment)
  end

end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_education.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Education: <%= @education.qualification %></h3>
  </div>
  <div class="panel-body">
    <p>
    <strong>institution:</strong>
    <%= @education.institution %>
    </p>

    <p>
    <strong>qualification:</strong>
    <%= @education.qualification %>
    </p>

    <p>
    <strong>subject:</strong>
    <%= @education.subject %>
    </p>

    <p>
    <strong>result:</strong>
    <%= @education.result %>
    </p>

    <p>
    <strong>start-date:</strong>
    <%= (@education.start_date).strftime("%b %Y") %>
    </p>

    <p>
    <strong>end-date:</strong>
    <%= (@education.end_date).strftime("%b %Y") %>
    </p>

  </div>
</div>

app/views/educations/_education_row.html.erb
<tr class="clickable" data-toggle="collapse" data-target=".<%= education_row.object_id %>" onclick="">
  <td style="border:0;"><%= education_row.institution %></td>
  <td style="border:0;"><%= education_row.qualification %></td>
  <td style="border:0;"><%= education_row.subject %></td>
  <td style="border:0;"><%= education_row.result %></td>
  <td class="hidden-xs" style="border:0;"><%= education_row.formatted_start_date %></td>
  <td class="hidden-xs" style="border:0;"><%= education_row.formatted_end_date %></td>
  <%- if current_user.admin_for?(education_row) %>
  <td style="border:0;">
    <div class="btn-group">
      <button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="border-radius:4px;height:60%;line-height:1">
        <span><i class="fa fa-chevron-down"></i></span>
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <ul class="dropdown-menu" style="text-align:left;min-width:70px">
        <li><%= link_to 'edit', edit_education_path(education_row) %></li>
        <li><%= link_to 'delete', education_path(education_row), method: :delete, data: { confirm: 'Are you sure?' } %></li>
      </ul>
    </div>
  </td>
  <% end %>
</tr>

app/views/educations/_educations_table.html.erb
<table class="table table-condensed table-hover" style="border-collapse:collapse;"> 
  <thead>
    <tr style="color:#999999;font-size:.8em">
      <th>institution</th>
      <th>qualification</th>
      <th>subject</th>
      <th>result</th>
      <th class="hidden-xs">start</th>
      <th class="hidden-xs">end</th>
      <%- if current_user.admin_for?(educations_table.first) %>
      <th colspan="3"></th>
      <% end %>
    </tr>
  </thead> 

  <tbody>
    <%= render partial: 'educations/education_row', collection: educations_table %>
  </tbody>
</table>

app/views/educations/_form.html.erb
<div class="panel-body">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6">
      <%= f.input :institution, required: true, placeholder: "School / College / University", label: "School / College / University" %>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6">
      <%= f.input :qualification, required: true, placeholder: "Qualification", label: "Qualification "%>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6">
      <%= f.input :subject, required: true, placeholder: "Subject", label: "Subject "%>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6">
      <%= f.input :result, required: true, placeholder: "Result", label: "Result "%>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6">
      <%= f.input :start_date, as: :date, end_year: Date.today.year, start_year: Date.today.year - 25, discard_day: true, order: [:month, :year] %>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6">
      <%= f.input :end_date, as: :date, end_year: Date.today.year, start_year: Date.today.year - 25, discard_day: true, order: [:month, :year] %>
    </div>
  </div>
  <hr>
  <div class="form-actions" style="text-align:center">
    <%= f.submit "Submit", class: 'btn btn-default' %>
  </div>
</div>

app/views/educations/edit.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-sm-offset-2 col-md-offset-3 col-lg-offset-3 col-lg-6 col-md-6 col-sm-8 col-xs-10">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 id="form-title">Edit Education
          <%= link_to 'back', :back, class:'pull-right', style:'padding-top:5px;font-size:.8em' %>
        </h3>
      </div>
      <%= simple_form_for([@education]) do |f| %>
        <%= render partial: 'educations/form', locals: {f: f} %>
      <% end %>
    </div>
  </div>
</div>

app/views/educations/index.html.erb
<%= render partial: 'educations/educations_table', object: @educations %>

<%= link_to 'Back', hunter_path(@hunter), :class => "btn btn-default btn-xs" %>

app/views/educations/new.html.erb
<div class="row">
  <div class="col-lg-offset-3 col-lg-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 id="form-title">New Education
          <%= link_to 'back', :back, class:'pull-right', style:'padding-top:5px;font-size:.8em' %>
        </h3>
      </div>
      <%= simple_form_for([@hunter, @education]) do |f| %>
        <%= render partial: 'educations/form', locals: {f: f} %>
      <% end %>
    </div>
  </div>
</div>

app/views/educations/show.html.erb
<div class="col-lg-8 col-lg-offset-2">
<%= render partial: '/educations/education', object: @education %>
</div>
<div class="col-lg-12 col-lg-offset-2">
<%= link_to 'Back', hunter_path(@education.hunter), class:"btn btn-default btn-xs" %>
</div>